drivers: gpu: drm: Drop unused function aee_kernel_exception_api
error: implicit declaration of function 'aee_kernel_exception_api' [-Werror,-Wimplicit-function-declaration]
        aee_kernel_exception_api(__FILE__, __LINE__, DB_OPT_DEFAULT|DB_OPT_MMPROFILE_BUFFER,
        ^
  CC      net/netfilter/xt_policy.o
../drivers/gpu/drm/mediatek/mtk_drm_crtc.c:2519:47: error: use of undeclared identifier 'DB_OPT_DEFAULT'
        aee_kernel_exception_api(__FILE__, __LINE__, DB_OPT_DEFAULT|DB_OPT_MMPROFILE_BUFFER,
                                                     ^
../drivers/gpu/drm/mediatek/mtk_drm_crtc.c:2519:62: error: use of undeclared identifier 'DB_OPT_MMPROFILE_BUFFER'
        aee_kernel_exception_api(__FILE__, __LINE__, DB_OPT_DEFAULT|DB_OPT_MMPROFILE_BUFFER,