drivers:scp: Supplement the missing scp_wdt_reset()
../drivers/misc/mediatek/sensor/2.0/mtk_nanohub/mtk_nanohub_ipi.c:109:4: error: implicit declaration of function 'scp_wdt_reset' [-Werror,-Wimplicit-function-declaration]
                        scp_wdt_reset(0);

Signed-off-by: HuaLiMao-AQ <hualimao_aq@163.com>